


; .seq
SECTION .stack; represents STACK                            ;AN000;
; END SECTION .stack;AN000;

SECTION .cseg_main; represents MAIN
; END SECTION .cseg_main

SECTION .cseg_open; represents  FASTOPEN                          ;AN000;
; END SECTION .cseg_open;AN000;

SECTION .cseg_seek; represents FASTSEEK                           ;AN000;
; END SECTION .cseg_seek;AN000;

SECTION .cseg_init; represents INIT
; END SECTION .cseg_init

