; .XLIST

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DOS - NLS Support - KEYB Command
;; (C) Copyright 1988 Microsoft
;;
;; File Name:  KEYBCMD.INC
;; ----------
;;
;; Root File Name:  KEYB.ASM
;; ---------------
;;
;; Description:
;; ------------
;;       External declarations for procedures in file KEYCMD.ASM.
;;
;; Change History:
;; ---------------
;;
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                                              ;;
        extern KEYB_COMMAND        ;;
                                              ;;
        extern KEYBSYS_FILE_HANDLE;;
        extern CP_TAB_OFFSET;;
        extern STATE_LOGIC_OFFSET;;
        extern SYS_CODE_PAGE;;
        extern KEYBCMD_LANG_ENTRY_PTR;;
        extern DESIG_CP_BUFFER;;
        extern DESIG_CP_OFFSET;;
        extern NUM_DESIG_CP;;
        extern TB_RETURN_CODE;;
	extern FILE_BUFFER_SIZE
        extern FILE_BUFFER;;
;****************CNS****************************
        extern ID_PTR_SIZE;;
;****************CNS****************************
        extern LANG_PTR_SIZE;;
        extern CP_PTR_SIZE;;
;****************CNS****************************
        extern NUM_ID;;
;****************CNS****************************
        extern NUM_LANG;;
        extern NUM_CP;;
        extern SHARED_AREA_PTR;;
        extern SD_SOURCE_PTR;;
        extern TEMP_SHARED_DATA;;
                                              ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; .LIST

