; .XLIST

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DOS - NLS Support - KEYB Command
;; (C) Copyright 1988 Microsoft
;;
;; File Name:  KEYBMSG.INC
;; ----------
;;
;; Root File Name:  KEYBCMD.ASM (KEYB.ASM)
;; ---------------
;;
;; Description:
;; ------------
;;	 External declarations for procedures in file KEYBCMD.ASM.
;;
;; Change History:
;; ---------------
;;
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
				       ;;
	extern ACT_KEYB_CP;;
	extern ACT_CON_CP;;
	extern ACT_KEYB;;
	extern INV_L;;
	extern INV_I;;
	extern INV_CP;;
	extern INV_S;;
	extern INV_FN;;
	extern INV_KEYB_Q;;
	extern INV_CON_Q;;
	extern NOT_DESIG;;
	extern NOT_SUPP;;
	extern NOT_VALID1;;
	extern NOT_VALID2;;
	extern WARNING_1;;
	extern INV_COMBO;;
	extern CR_LF;;
	extern MEMORY_OVERF;;
				       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; .LIST
