; .XLIST

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DOS - NLS Support - KEYB Command
;; (C) Copyright 1988 Microsoft
;;
;; File Name:  KEYBI9C.INC
;; ----------
;;
;; Root File Name:  KEYB.ASM
;; ---------------
;;
;; Description:
;; ------------
;;	 External declarations and equates for procedures in file
;;	 KEYBI9C.ASM
;;
;; Change History:
;; ---------------
;;
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
				       ;;
	extern KEYB_INT_9;;
	extern BUFFER_FILL;;
	extern ERROR_BEEP;;
	extern COUNTRY_FLAG;;
	extern BEEP_PENDING;;
	extern SCAN_CODE;;
	extern K8;;
	extern TEMP_HEAD;;
	extern TEMP_TAIL;;
	extern BUSY_TFLAG;;
	extern MYBUFF;;
	extern ENABLE_FL;;
	extern NEW_BUFF_CTR;;
				       ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; .LIST

