SECTION .CODE;AN000;segment for near routine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        global _MAIN;AN000;
_MAIN:;AN000;
        RET                             ;AN000;
; ENDP _MAIN;AN000;
                                        ;
        global INDBC;AN000;
INDBC:;AN000;
        RET                             ;AN000;
; ENDP INDBC;AN000;
                                        ;
        global BOXDR;AN000;
BOXDR:;AN000;
        RET                             ;AN000;
; ENDP BOXDR;AN000;
                                        ;
        global GRAPH;AN000;
GRAPH:;AN000;
        RET                             ;AN000;
; ENDP GRAPH;AN000;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; END SECTION .CODE;AN000;
        ; END;AN000;

